[workspace]
resolver = "2"
members = ["crates/core", "crates/app"]

[workspace.package]
version = "0.2.6"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
authors = ["playhard.pro <rex@playhard.pro>"]
homepage = "https://github.com/playhard-pro"
repository = "https://github.com/playhard-pro/net-tools"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
socket2 = { version = "0.6", features = ["all"] }
time = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
opt-level = 3
lto = "thin"
strip = true
